import { useState } from 'react';
import { CompanyFinancials, MergerAssumptions, MergerResults } from '../types';
import { ExportModal } from './ExportModal';

interface ExportButtonProps {
  acquirer: CompanyFinancials;
  target: CompanyFinancials;
  assumptions: MergerAssumptions;
  results: MergerResults;
}

function formatCurrency(value: number): string {
  return `$${value.toFixed(2)}`;
}

function formatPercent(value: number): string {
  return `${value.toFixed(2)}%`;
}

function generateTextReport(
  acquirer: CompanyFinancials,
  target: CompanyFinancials,
  assumptions: MergerAssumptions,
  results: MergerResults
): string {
  const timestamp = new Date().toLocaleDateString();

  return `
M&A MERGER ANALYSIS REPORT
Generated: ${timestamp}

═══════════════════════════════════════════════════════════

TRANSACTION OVERVIEW
─────────────────────────────────────────────────────────

Acquirer:              ${acquirer.name}
Target:                ${target.name}
Offer Price/Share:     ${formatCurrency(results.offerPrice)}
Total Consideration:   ${formatCurrency(results.totalConsideration)}M
  - Cash:              ${formatCurrency(results.cashPortion)}M (${assumptions.cashPercent}%)
  - Stock:             ${formatCurrency(results.stockPortion)}M (${assumptions.stockPercent}%)
Premium:               ${formatPercent(assumptions.premiumPercent)}


PRO FORMA FINANCIALS
─────────────────────────────────────────────────────────

Revenue:               ${formatCurrency(results.proFormaRevenue)}M
EBITDA:                ${formatCurrency(results.proFormaEbitda)}M
Net Income:            ${formatCurrency(results.proFormaNetIncome)}M
Total Shares:          ${results.proFormaTotalShares.toFixed(2)}M
EPS:                   ${formatCurrency(results.proFormaEps)}


OWNERSHIP STRUCTURE
─────────────────────────────────────────────────────────

${acquirer.name}:      ${formatPercent(results.acquirerOwnership)}
${target.name}:        ${formatPercent(results.targetOwnership)}


ACCRETION / DILUTION ANALYSIS
─────────────────────────────────────────────────────────

Standalone EPS:        ${formatCurrency(results.acquirerStandaloneEps)}
Pro Forma EPS:         ${formatCurrency(results.proFormaEps)}
EPS Change:            ${formatCurrency(results.epsChange)} (${formatPercent(results.epsChangePercent)})
Transaction Impact:    ${results.isAccretive ? 'ACCRETIVE ✓' : 'DILUTIVE ✗'}


VALUATION METRICS
─────────────────────────────────────────────────────────

Pro Forma Market Cap:  ${formatCurrency(results.proFormaMarketCap)}M
Enterprise Value:      ${formatCurrency(results.proFormaEnterpriseValue)}M
Estimated IRR:         ${formatPercent(results.estimatedIrr)}


ASSUMPTIONS
─────────────────────────────────────────────────────────

Cost Synergies:        ${formatCurrency(assumptions.synergyCost)}M
Revenue Synergies:     ${formatCurrency(assumptions.synergyRevenue)}M
New Debt Financing:    ${formatCurrency(assumptions.debtFinancingAmount)}M
Debt Interest Rate:    ${formatPercent(assumptions.debtInterestRate)}

═══════════════════════════════════════════════════════════

Generated by M&A Merger Simulator
  `.trim();
}

export function ExportButton({ acquirer, target, assumptions, results }: ExportButtonProps) {
  const [showModal, setShowModal] = useState(false);

  const handleExportText = () => {
    const report = generateTextReport(acquirer, target, assumptions, results);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `merger-analysis-${acquirer.name}-${target.name}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    const csv = [
      ['Metric', 'Value'],
      ['Acquirer', acquirer.name],
      ['Target', target.name],
      ['Offer Price per Share', results.offerPrice],
      ['Total Consideration (M)', results.totalConsideration],
      ['Cash Portion (M)', results.cashPortion],
      ['Stock Portion (M)', results.stockPortion],
      ['Premium (%)', assumptions.premiumPercent],
      ['Pro Forma Revenue (M)', results.proFormaRevenue],
      ['Pro Forma EBITDA (M)', results.proFormaEbitda],
      ['Pro Forma Net Income (M)', results.proFormaNetIncome],
      ['Pro Forma EPS', results.proFormaEps],
      ['Standalone EPS', results.acquirerStandaloneEps],
      ['EPS Change', results.epsChange],
      ['EPS Change (%)', results.epsChangePercent],
      ['Transaction Impact', results.isAccretive ? 'Accretive' : 'Dilutive'],
      ['Acquirer Ownership (%)', results.acquirerOwnership],
      ['Target Ownership (%)', results.targetOwnership],
      ['Pro Forma Market Cap (M)', results.proFormaMarketCap],
      ['Enterprise Value (M)', results.proFormaEnterpriseValue],
      ['Estimated IRR (%)', results.estimatedIrr],
      ['Cost Synergies (M)', assumptions.synergyCost],
      ['Revenue Synergies (M)', assumptions.synergyRevenue],
    ]
      .map(row => row.join(','))
      .join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `merger-analysis-${acquirer.name}-${target.name}-${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <>
      <div className="export-buttons">
        <button onClick={() => setShowModal(true)} className="export-btn">
          Export Results
        </button>
      </div>

      {showModal && (
        <ExportModal
          acquirer={acquirer}
          target={target}
          assumptions={assumptions}
          results={results}
          onClose={() => setShowModal(false)}
        />
      )}
    </>
  );
}
